import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const API='http://localhost:8000';
const number=n=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:0}).format(Math.abs(n));
const signed=n=>`${n>0?'+':n<0?'−':''}${number(n)}`;
const date=d=>new Date(d+'T12:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short'});
const period=r=>r?`${Number(r.period_start.slice(8))}–${date(r.period_end)}, ${r.report_date.slice(0,4)}`:'Choose a period';
const sum=rows=>rows.reduce((s,r)=>s+r.equityNetInvestmentCr,0);
const tone=n=>n>0?'positive':n<0?'negative':'neutral';
const transition=(a,b)=>a==null?'No earlier report':a===0||b===0?'Includes a flat period':a>0&&b>0?'Continued inflow':a<0&&b<0?'Continued outflow':b>0?'Turned to inflow':'Turned to outflow';

async function request(path, options){const r=await fetch(API+path,options);const data=await r.json();if(!r.ok)throw Error(data.error||'Unable to load reports');return data;}

function App(){
 const [reports,setReports]=useState([]),[all,setAll]=useState([]),[selected,setSelected]=useState(''),[view,setView]=useState('Overview'),[sector,setSector]=useState(''),[query,setQuery]=useState(''),[compare,setCompare]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 const load=async()=>{try{const [r,f]=await Promise.all([request('/api/reports'),request('/api/flows')]);setReports(r);setAll(f);setSelected(s=>r.some(x=>x.report_date===s)?s:r[0]?.report_date||'');setCompare(s=>r.some(x=>x.report_date===s)?s:r[1]?.report_date||r[0]?.report_date||'');setSector(s=>s||f[0]?.sectorName||'');setError('');}catch(e){setError('Could not load your reports. '+e.message);}finally{setLoading(false);}};
 useEffect(()=>{load()},[]);
 const upload=async e=>{const files=[...e.target.files];if(!files.length)return;setBusy(true);setMessage('');const results=[];for(const f of files){try{const body=new FormData();body.append('file',f);const d=await request('/api/reports/import',{method:'POST',body});results.push(`${f.name}: added ${d.sectorCount} sectors`);}catch(e){results.push(`${f.name}: ${e.message}`);}}await load();setMessage(results.join(' · '));setBusy(false);e.target.value='';};
 const report=reports.find(r=>r.report_date===selected), previous=reports[reports.findIndex(r=>r.report_date===selected)+1];
 const flows=all.filter(f=>f.reportDate===selected).sort((a,b)=>b.equityNetInvestmentCr-a.equityNetInvestmentCr), before=all.filter(f=>f.reportDate===previous?.report_date);
 const total=report?.totalNet??sum(flows), prevTotal=previous?.totalNet??sum(before), positive=flows.filter(f=>f.equityNetInvestmentCr>0),negative=flows.filter(f=>f.equityNetInvestmentCr<0);
 const sectors=[...new Set(all.map(f=>f.sectorName))].sort(), history=all.filter(f=>f.sectorName===sector).sort((a,b)=>a.reportDate.localeCompare(b.reportDate));
 const inspect=name=>{setSector(name);setView('Sector detail');};
 const comparison=all.filter(f=>f.reportDate===compare);
 const differences=flows.map(f=>{const old=comparison.find(x=>x.sectorName===f.sectorName);return {...f,old,delta:old?f.equityNetInvestmentCr-old.equityNetInvestmentCr:null};}).sort((a,b)=>(b.delta??-Infinity)-(a.delta??-Infinity));
 return <div className="shell"><aside><a className="brand" href="#" onClick={()=>setView('Overview')}><span className="brand-icon">↗</span> flowfolio<span className="brand-dot">.</span></a><div className="workspace">YOUR MARKET NOTEBOOK</div><nav>{[['Overview','◫'],['Sector heatmap','▦'],['Sector detail','⌁'],['Compare periods','⇄'],['Reports','▤']].map(([name,icon])=><button key={name} className={view===name?'active':''} onClick={()=>setView(name)}><span>{icon}</span>{name}</button>)}</nav><div className="sidebar-note"><span className="status-dot"/> Local & personal<p>Your reports stay on this computer.</p></div></aside>
 <main><div className="topbar"><span>INDIAN EQUITIES <span className="separator">/</span> FOREIGN INVESTOR FLOWS</span><span className="source">● NSDL reports</span></div><header><div><div className="eyebrow">FOLLOW THE MONEY, EVERY FORTNIGHT</div><h1>{view==='Overview'?'Where is the money moving?':view==='Sector heatmap'?'The bigger picture.':view==='Sector detail'?'Get to know a sector.':view==='Compare periods'?'What changed between periods?':'Your report library.'}</h1><p>Understand where foreign investors are adding money—and where they are pulling back.</p></div><label className="upload">{busy?'Importing…':'+ Add report'}<input disabled={busy} type="file" multiple accept=".html,.htm,text/html" onChange={upload}/></label></header>
 {error&&<div className="alert" role="alert">{error} <button onClick={load}>Try again</button></div>}{message&&<div className="notice" role="status">{message}</div>}
 {loading?<div className="panel empty">Loading your reports…</div>:!reports.length?<div className="panel empty"><div className="empty-icon">▤</div><h2>Your first insight starts with a report.</h2><p>Add a fortnightly NSDL HTML report using “Add report”. You can select several files together.</p></div>:<><div className="toolbar"><label>Reporting period<select value={selected} onChange={e=>setSelected(e.target.value)}>{reports.map(r=><option key={r.id} value={r.report_date}>{period(r)}{r===reports[0]?' · Latest':''}</option>)}</select></label><div className="toolbar-right"><span className="badge">FPI · Equity</span><a className="export" href={`${API}/export/${report.id}`}>↓ Download Excel</a></div></div>
 {view==='Overview'&&<><div className="metrics"><section className="hero-card"><div className="card-label">TOTAL NET FLOW <span>₹ crore</span></div><div className="big-number">{total<0?'−':total>0?'+':''}₹{number(total)}<small>Cr</small></div><div className="hero-caption">{total<0?'More money moved out than in':total>0?'More money moved in than out':'Money in and out was balanced'}</div><div className="hero-bottom">{previous?`${total-prevTotal>=0?'↑':'↓'} ₹${number(total-prevTotal)} Cr ${total>=prevTotal?'higher':'lower'} than ${period(previous)}`:'Add an earlier report to see the change'}</div></section><section className="metric-card"><div className="card-label">MONEY MOVING IN <span className="circle positive">↗</span></div><strong>{positive.length}<small> / {flows.length} sectors</small></strong><p>Foreign investors added money</p><div className="meter"><i style={{width:`${positive.length/flows.length*100}%`}}/></div></section><section className="metric-card"><div className="card-label">MONEY MOVING OUT <span className="circle negative">↘</span></div><strong>{negative.length}<small> / {flows.length} sectors</small></strong><p>Foreign investors withdrew money</p><div className="meter red"><i style={{width:`${negative.length/flows.length*100}%`}}/></div></section></div>
 <div className="insight"><span>✦</span><p><b>This fortnight at a glance.</b> {positive.length>negative.length?'More sectors received money than lost money.':negative.length>positive.length?'Outflows were spread across more sectors than inflows.':'The number of sectors with inflows and outflows was equal.'} {positive[0]&&`${positive[0].sectorName} led inflows.`} {negative.length>0&&`${negative.at(-1).sectorName} saw the largest outflow.`}</p></div>
 <div className="two-columns"><Ranking title="Where money moved in" subtitle="Largest positive net investments" rows={positive.slice(0,5)} onSelect={inspect}/><Ranking title="Where money moved out" subtitle="Largest negative net investments" rows={[...negative].reverse().slice(0,5)} onSelect={inspect}/></div>
 <section className="panel"><div className="section-header"><div><h2>Every sector, at a glance</h2><p>Tap a sector to explore its history. All amounts in ₹ crore.</p></div><input className="search" aria-label="Search sectors" placeholder="Search a sector…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="table-wrap"><table><thead><tr><th>Sector</th><th>Net flow</th><th>Change vs previous</th><th>Direction</th></tr></thead><tbody>{flows.filter(f=>f.sectorName.toLowerCase().includes(query.toLowerCase())).map(f=>{const b=before.find(b=>b.sectorName===f.sectorName);return <tr key={f.id}><td><button className="text-button" onClick={()=>inspect(f.sectorName)}>{f.sectorName} <span>↗</span></button></td><td className={tone(f.equityNetInvestmentCr)}>{signed(f.equityNetInvestmentCr)}</td><td>{b?signed(f.equityNetInvestmentCr-b.equityNetInvestmentCr):'—'}</td><td><span className="direction">{transition(b?.equityNetInvestmentCr,f.equityNetInvestmentCr)}</span></td></tr>})}</tbody></table></div></section></>}
 {view==='Sector heatmap'&&<section className="panel"><div className="section-header"><div><h2>Follow the flow over time</h2><p>Each cell is one sector’s net investment. Darker shades mean larger flows.</p></div><span className="legend"><i/> Outflow <i/> Inflow</span></div><div className="table-wrap heatmap"><table><thead><tr><th>Sector / ₹ crore</th>{[...reports].reverse().map(r=><th key={r.id}>{date(r.report_date)}<small>{r.report_date.slice(0,4)}</small></th>)}<th>Cumulative</th></tr></thead><tbody>{sectors.map(s=><tr key={s}><td><button className="text-button" onClick={()=>inspect(s)}>{s}</button></td>{[...reports].reverse().map(r=>{const v=all.find(f=>f.sectorName===s&&f.reportDate===r.report_date)?.equityNetInvestmentCr;const max=Math.max(...all.map(x=>Math.abs(x.equityNetInvestmentCr)),1);return <td key={r.id} style={{background:v==null?'#f4f5f6':v>=0?`rgba(36,149,116,${0.08+Math.abs(v)/max*.7})`:`rgba(225,97,81,${0.08+Math.abs(v)/max*.7})`}}>{v==null?'—':signed(v)}</td>})}<td>{signed(sum(all.filter(f=>f.sectorName===s)))}</td></tr>)}</tbody></table></div></section>}
 {view==='Sector detail'&&<><section className="panel"><div className="section-header"><div><h2>A closer look</h2><p>History across all {reports.length} available reporting periods.</p></div><select aria-label="Sector" value={sector} onChange={e=>setSector(e.target.value)}>{sectors.map(s=><option key={s}>{s}</option>)}</select></div><h2 className="sector-title">{sector}</h2><div className="detail-metrics"><div><small>Selected period · Net flow</small><strong className={tone(flows.find(f=>f.sectorName===sector)?.equityNetInvestmentCr||0)}>{signed(flows.find(f=>f.sectorName===sector)?.equityNetInvestmentCr||0)} Cr</strong></div><div><small>Cumulative · {history.length} available periods</small><strong>{signed(sum(history))} Cr</strong></div><div><small>Periods with inflows</small><strong>{history.filter(f=>f.equityNetInvestmentCr>0).length} / {history.length}</strong></div></div></section><div className="two-columns"><section className="panel"><h2>Money in and money out</h2><p>Fortnightly net investment · ₹ crore</p><Bars rows={history} field="equityNetInvestmentCr"/></section><section className="panel"><h2>Holdings at period end</h2><p>Equity AUC · ₹ crore · includes market-price effects</p><Bars rows={history} field="equityAucCr"/></section></div><section className="panel table-wrap"><table><thead><tr><th>Report ending</th><th>Net investment · Cr</th><th>Equity AUC · Cr</th></tr></thead><tbody>{history.map(f=><tr key={f.id}><td>{date(f.reportDate)} {f.reportDate.slice(0,4)}</td><td className={tone(f.equityNetInvestmentCr)}>{signed(f.equityNetInvestmentCr)}</td><td>{number(f.equityAucCr)}</td></tr>)}</tbody></table></section></>}
 {view==='Compare periods'&&<section className="panel"><div className="section-header"><div><h2>Selected period vs an earlier snapshot</h2><p>Change = selected fortnight minus comparison fortnight. All values in ₹ crore.</p></div><label>Compare with<select value={compare} onChange={e=>setCompare(e.target.value)}>{reports.map(r=><option key={r.id} value={r.report_date}>{period(r)}</option>)}</select></label></div>{selected===compare&&<p className="notice">Choose two different periods to see what changed.</p>}<div className="table-wrap"><table><thead><tr><th>Sector</th><th>{date(compare)} flow</th><th>{date(selected)} flow</th><th>Change</th><th>AUC then → now</th></tr></thead><tbody>{differences.map(f=><tr key={f.id}><td><button className="text-button" onClick={()=>inspect(f.sectorName)}>{f.sectorName}</button></td><td>{f.old?signed(f.old.equityNetInvestmentCr):'—'}</td><td>{signed(f.equityNetInvestmentCr)}</td><td className={tone(f.delta)}>{f.delta==null?'—':signed(f.delta)}</td><td>{f.old?number(f.old.equityAucCr):'—'} → {number(f.equityAucCr)}</td></tr>)}</tbody></table></div></section>}
 {view==='Reports'&&<section className="panel"><h2>Your saved fortnights</h2><p>Add a new HTML report every fortnight. Existing dates are protected from duplicate imports.</p>{reports.map(r=><div className="report-row" key={r.id}><span className="document-icon">▤</span><div><b>{period(r)}</b><small>{r.filename}</small></div><span className="badge">Imported</span><a className="export" href={`${API}/export/${r.id}`}>↓ Excel</a></div>)}</section>}
 <div className="explainer"><b>A little context goes a long way.</b><p><b>FPI</b> means foreign portfolio investors. <b>Net flow</b> is their investment minus withdrawals—not gross purchases or sales. <b>AUC</b> is the value of holdings at the end of a period; it also changes with market prices. Figures are in ₹ crore.</p></div><footer><span>Source: your uploaded NSDL reports · {reports.length} periods</span><span>Historical data, not investment advice.</span></footer></>}
 </main></div>;
}
function Ranking({title,subtitle,rows,onSelect}){const max=Math.max(...rows.map(r=>Math.abs(r.equityNetInvestmentCr)),1);return <section className="panel"><h2>{title}</h2><p>{subtitle} <span className="unit">₹ crore</span></p>{!rows.length?<p>No sectors in this direction.</p>:rows.map((r,i)=><button className="ranking-row" key={r.id} onClick={()=>onSelect(r.sectorName)}><span className="rank-number">{String(i+1).padStart(2,'0')}</span><span className="rank-body"><span className="rank-line"><b>{r.sectorName}</b><strong className={tone(r.equityNetInvestmentCr)}>{signed(r.equityNetInvestmentCr)} <span>↗</span></strong></span><span className={`rank-track ${tone(r.equityNetInvestmentCr)}`}><i style={{width:`${Math.abs(r.equityNetInvestmentCr)/max*100}%`}}/></span></span></button>)}</section>}
function Bars({rows,field}){const max=Math.max(...rows.map(r=>Math.abs(r[field])),1);return <div className="bars">{rows.map(r=><div key={r.id} className="chart-row"><span>{date(r.reportDate)}</span><div className="bar-track"><i className={tone(r[field])} style={{width:`${Math.abs(r[field])/max*100}%`}}/></div><b className={tone(r[field])}>{field==='equityAucCr'?number(r[field]):signed(r[field])}</b></div>)}</div>}
createRoot(document.getElementById('root')).render(<App/>);
